<a href="https://colab.research.google.com/github/prodigyxiao/Coursera_Intro-to-DS-in-Py/blob/master/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
**Coursera:** Introduction to Data Science in Python -- University of Michigan



_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [0]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


<br>
`add_numbers` updated to take an optional flag parameter.

In [0]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


<br>
Assign function `add_numbers` to variable `a`.

In [0]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

# The Python Programming Language: Types and Sequences

Use `type` to return the object's type.

In [0]:
type('This is a string')

str

In [0]:
type(None)

NoneType

In [0]:
type(1)

int

In [0]:
type(1.0)

float

In [0]:
type(add_numbers)

function

<br>
Tuples are an immutable data structure (cannot be altered).

In [0]:
x = (1, 'a', 2, 'b')
type(x)

tuple

<br>
Lists are a mutable data structure.

In [0]:
y = [1, 'a', 2, 'b']
type(y)

list

<br>
Use `append` to append an object to a list.

In [0]:
y.append(3.3)
print(y)

[1, 'a', 2, 'b', 3.3]


<br>
This is an example of how to loop through each item in the list.

In [0]:
for item in y:
    print(item)

1
a
2
b
3.3


<br>
Or using the indexing operator:

In [0]:
i=0
while( i != len(y) ):
    print(y[i])
    i = i + 1

1
a
2
b
3.3


<br>
Use `+` to concatenate lists.

In [4]:
[1,2] + [3,4]

[1, 2, 3, 4]

<br>
Use `*` to repeat lists.

In [3]:
[1]*3

[1, 1, 1]

<br>
Use the `in` operator to check if something is inside a list.

In [2]:
1 in [1, 2, 3]

True

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [1]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


T
T
Th


This will return the last element of the string.

In [5]:
x[-1]

'g'

This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [6]:
x[-4:-2]

'ri'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [7]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 4th element of the string and going all the way to the end.

In [8]:
x[3:]

's is a string'

In [9]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [10]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


<br>
Make sure you convert objects to strings before concatenating.

In [11]:
'Chris' + 2

TypeError: ignored

In [12]:
'Chris' + str(2)

'Chris2'

<br>
Dictionaries associate keys with values.

In [3]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [0]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

<br>
Iterate over all of the keys:

In [5]:
for name in x:
    print(name +': '+ str(x[name]))
    print(x[name])

Christopher Brooks: brooksch@umich.edu
brooksch@umich.edu
Bill Gates: billg@microsoft.com
billg@microsoft.com
Kevyn Collins-Thompson: None
None


**Iterate over all of the values:**

In [6]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


**Iterate over all of the items in the list:**

In [7]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


<br>
You can unpack a sequence into different variables:

In [0]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [0]:
fname

In [0]:
lname

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [8]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: ignored

# The Python Programming Language: More on Strings

In [0]:
print('Chris' + 2)

In [0]:
print('Chris' + str(2))

<br>
Python has a built in method for convenient string formatting.

In [0]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [0]:
import csv

%precision 2  # float precison set as 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [0]:
len(mpg)

<br>
`keys` gives us the column names of our csv.

In [0]:
mpg[0].keys()

**Find the average cty fuel economy across all cars. **
All values in the dictionaries are strings, so we need to convert to float.

In [0]:
sum(float(d['cty']) for d in mpg) / len(mpg)

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [0]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

**Use `set` to return the unique values for the number of cylinders the cars in our dataset have.**

In [0]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

**Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.**

In [0]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0]) # use the first element in CtyMpgByCyl to sort
CtyMpgByCyl

<br>
Use `set` to return the unique values for the class types in our dataset.

In [0]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

**Here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.**

In [0]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

<br>
# The Python Programming Language: Dates and Times

In [0]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [0]:
tm.time()

<br>
Convert the timestamp to datetime.

In [0]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

<br>
Handy datetime attributes:

In [0]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

<br>
`timedelta` is a duration expressing the difference between two dates.

In [0]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

<br>
`date.today` returns the current local date.

In [0]:
today = dt.date.today()

In [0]:
today - delta # the date 100 days ago

In [0]:
today > today-delta # compare dates

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [0]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [0]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

**Here's an example of mapping the `min` function between two lists.**

In [10]:
"""
The map function returns to you a map object. 
It doesn't actually try and run the function min 
on two items, until you look inside for a value.
This is an interesting design pattern of the language, 
and it's commonly used when dealing with big data. 
This allows us to have very efficient memory management, 
even though something might be computationally complex.
"""
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2) # lazy evaluation
cheapest # return a map object

<br>
Now let's iterate through the map object to see the values.

In [11]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


Quiz: Here is a list of faculty teaching this MOOC. Can you write a function and apply it using map() to get a list of all faculty titles and last names (e.g. ['Dr. Brooks', 'Dr. Collins-Thompson', …]) ?

In [12]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split(' ')[0]+' '+person.split(' ')[2]#Your answer here

list(map(split_title_and_name, people))#Your answer here

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vinod', 'Dr. Romero']

<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [0]:
my_function = lambda a, b, c : a + c

In [16]:
my_function(1, 2, 3)

4

Quiz: Convert this function into a lambda:

In [17]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

Let's iterate from 0 to 9 and return the even numbers.

In [18]:
my_list = []
for number in range(0, 10):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

<br>
Now the same thing but with list comprehension.

In [19]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

Quiz: Convert a function into a list comprehension.

In [20]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

Quiz: Imagine you work at an internet service provider and the user ids are all two letters followed by two numbers (e.g. aa49). Write an initialization line as a single list comprehension which creates a list of all possible user ids. Assume the letters are all lower case.

In [0]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [0]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [24]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [25]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [26]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [27]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [28]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [29]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [30]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [31]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [32]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [33]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.**

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**`diag` extracts a diagonal or constructs a diagonal array.**

In [35]:
np.diag(y) # 对角矩阵

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [36]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [37]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [38]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

**Use `vstack` to stack arrays in sequence vertically (row wise).**

In [39]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

**Use `hstack` to stack arrays in sequence horizontally (column wise).**

In [40]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [42]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [43]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [44]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [45]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [46]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [49]:
z = np.array([y, y**2])
print(z)
print(len(z)) # number of rows of array

[[ 4  5  6]
 [16 25 36]]
2


<br>
The shape of array `z` is `(2,3)` before transposing.

In [48]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [50]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [51]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [52]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [53]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [55]:
a = np.array([-4, -2, 1, 3, 5])
print(a)

[-4 -2  1  3  5]


In [0]:
a.sum()

In [0]:
a.max()

In [0]:
a.min()

In [0]:
a.mean()

In [0]:
a.std()

`argmax` and `argmin` return the** index** of the maximum and minimum values in the array.

In [56]:
a.argmax()

4

In [57]:
a.argmin()

0

<br>
## Indexing / Slicing

In [58]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [0]:
s[0], s[4], s[-1]

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

<br>
Use negatives to count from the back.

In [0]:
s[-4:]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [0]:
r = np.arange(36)
r.resize((6, 6))
r

<br>
Use bracket notation to slice: `array[row, column]`

In [0]:
r[2, 2]

<br>
And use : to select a range of rows or columns

In [0]:
r[3, 3:6]

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [0]:
r[:2, :-1]

<br>
This is a slice of the last row, and only every other element.

In [0]:
r[-1, ::2]

We can also perform **conditional indexing**. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [0]:
r[r > 30]

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [0]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [0]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [0]:
r2[:] = 0
r2

**`r` has also been changed!**

In [0]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [0]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [0]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [59]:
test = np.random.randint(0, 10, (4,3))
test

array([[7, 2, 4],
       [0, 2, 8],
       [9, 1, 5],
       [6, 3, 9]])

<br>
Iterate by row:

In [60]:
for row in test:
    print(row)

[7 2 4]
[0 2 8]
[9 1 5]
[6 3 9]


<br>
Iterate by index:

In [61]:
for i in range(len(test)):
    print(test[i])

[7 2 4]
[0 2 8]
[9 1 5]
[6 3 9]


**Iterate by row and index:**

In [62]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [7 2 4]
row 1 is [0 2 8]
row 2 is [9 1 5]
row 3 is [6 3 9]


<br>
Use `zip` to iterate over multiple iterables.

In [63]:
test2 = test**2
test2

array([[49,  4, 16],
       [ 0,  4, 64],
       [81,  1, 25],
       [36,  9, 81]])

In [64]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[7 2 4] + [49  4 16] = [56  6 20]
[0 2 8] + [ 0  4 64] = [ 0  6 72]
[9 1 5] + [81  1 25] = [90  2 30]
[6 3 9] + [36  9 81] = [42 12 90]
